spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/scg-chat?useSSL=false&serverTimezone=UTC
    username: root
    password: tnfyd!23
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
  api-docs:
    path: /api-docs
